### ISSUE TITLE
Indication when @RobotKeyword annotation of a private method

### ISSUE THREAD

**Issue by davidmerrick** [jivesoftware/robot-intellij-plugin#41]
Sometimes, the @RobotKeyword annotation is added to a private Java method. When this happens, the plugin will autofill the keyword in a test without indicating that it can't be used. There should be some red underlining under the Java method to alert about this, and not index those keywords for autofilling.

**Comment by charlescapps** [comment]
Yeah, good point. This is pretty straightforward to implement,  I'll do it
at some time soonish.

**Comment by charlescapps** [comment]
Is done! Download version 1.7.0 and this will work. Also highlight methods in red if they aren't in a class annotated with @RobotKeywords, or if that class isn't public.

https://plugins.jetbrains.com/update/index?pr=idea&updateId=18616
